### ISSUE TITLE
pangram: return code of a false result

### ISSUE THREAD

**Issue by ZapAnton** [exercism/bash#241]
In the `pangram` exercise each test expects that the tested function returns `0` status code, regardless if the passed string is a pangram or not.

But earlier in the `armstrong-numbers` exercise if the number is not an armstrong number the tested function is expected to return `1` status code.

Should the `pangram` test suite be changed to expect `1` status code for consistency?

**Comment by guygastineau** [comment]
It was a conscious decision.  Before I believe it relied solely on the exit status to judge the truthiness, but in order to be consistent it was decided that exercises should return text output.

Since the program is functioning correctly if it returns either true or false it isn't really an error when it returns false.

Therefore, an exit code of 0 for non-error returns makes the best policy.

Other exercises have also been updated to adhere to this policy.

**Comment by budmc29** [comment]
@ZapAnton if you want, feel free to look at the exercises and see if there is any inconsistent application of that rule and create a PR.
