### ISSUE TITLE
The meaning of the stdout tag

### ISSUE THREAD

**Issue by ZapAnton** [exercism/bash#250]
Couldn't find any sort of discussion about the issue, but feel free to close it if this is a duplicate.

My question is what is the meaning behind `stdout` tag in the exercises?

Every exercise is organized to test the content of the stdout, but only a few are marked with this tag.

If this tag is used to show that some special string is expected as an output then why `nucleotide-count` or `rna-transcription` are not tagged with it?

**Comment by guygastineau** [comment]
This is a good point.  The nature of the Bash has us testing stdout where other languages would just be testing return values with the programs API.

I think there is no reason for this tag in our track since it is implied by the nature of Bash and our tests.

Let's see what some others think before acting, but I think this will turn into a PR to remove those tags.  In that case I would like to label it `good first patch`, so that hopefully someone newer to GitHub could get a little experience with a simple patch like this.

**Comment by guygastineau** [comment]
I added the good first patch label.

If it doesn't seem like there are any new takers in a couple days, then please feel free to do this.

PS. If anyone the thinks this shouldn't have that label please voice your opinion.

Thanks

**Comment by guygastineau** [comment]
It doesn't seem like we have any first time takers on this. I'll remove the label when I'm back at my computer.
