### ISSUE TITLE
bats not working?

### ISSUE THREAD

**Issue by stantoncbradley** [exercism/bash#252]
Hi! Thanks for an awesome project! I've been using exercism for years :D really dig the new format!

I'm trying to work through the bash track, but the bats test suite doesn't work for me :(

```
@test "1" {
  #skip
  run bash grains.sh 1
  [ "$status" -eq 0 ]
  [ "$output" == "1" ]
}

➜  bash git:(master) ✗ bats grains/grains_test.sh

 ✗ 1
   (in test file grains/grains_test.sh, line 6)
     `[ "$status" -eq 0 ]' failed
```
then I changed it to
```
@test "1" {
  #skip
  run bash grains.sh 1
  [ "$?" -eq 0 ]
  [ "$output" == "1" ]
}
➜  bash git:(master) ✗ bats grains/grains_test.sh

 ✗ 1
   (in test file grains/grains_test.sh, line 7)
     `[ "$output" == "1" ]' failed
````
any ideas why the test suite and/or bats isn't working for me?

MacOS High Sierra 10.13.2
Bats 0.4.0
Homebrew 1.7.4
Homebrew/homebrew-core (git revision ba17c; last commit 2018-09-14)
Homebrew/homebrew-cask (git revision 1227; last commit 2018-09-13)

Thanks!

**Comment by stantoncbradley** [comment]
Here is the code, btw
```
#!/bin/bash

if [[ ! ("$1" =~ ^[0-9]+$) ]] || (( $1 < 1 || $1 > 64  )); then
	echo "Error: invalid input"
	exit 1
else
	echo $(( 2**($1-1) ))
fi
```
copy/pasted straight from someone else's working solution

**Comment by budmc29** [comment]
Looks like the solution you provided does not work on my Mac as well, it could be a solution that works fine on a Linux machine, but because of the bash number overflow (I don't know the exact name for the issue): https://superuser.com/questions/1030122/what-is-the-maximum-value-of-a-numeric-bash-shell-variable.

You can try and solve the issue yourself, or have a look here for a valid solution: https://github.com/exercism/bash/blob/master/exercises/grains/example.sh

Looks like `bats` works as expected in this situation.

**Comment by stantoncbradley** [comment]
figured it out! was running the command from a directory up, needed to be in the directory to pick up the file path
