### ISSUE TITLE
Additional Test for ISBN-Verifier Exercise on Bash Track

### ISSUE THREAD

**Issue by Ric0chet-GitHub** [exercism/bash#353]
The test suite for this exercise currently doesn't check for the case of an otherwise valid ISBN with an embedded invalid character (containing 11 characters):
```
@test 'valid isbn number containing invalid character' {
  #[[ $BATS_RUN_SKIPPED == true  ]] || skip
  run bash isbn_verifier.sh '3-598-21P508-8'
  [[ $status -eq 0 ]]
  [[ $output == 'false' ]]
}
```
I'm assuming this should return "false."  While submitting my current solution, I realized that it would fail such a test.

Thanks,
-Logan

**Comment by kotp** [comment]
This may be true for tracks in general.  Can you check [this file](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json) and see if there isn't a test missing from there?  I see a test that is similar, though it uses "X" instead of "P".

If this is true from the canonical data, then we need to add it in there and regenerate the tests here.

**Comment by NobbZ** [comment]
`X` is a character that is valid at the last (first(?)) digit of the ISBN and does mean a value of `10` for that digit IIRC.

The test in the canonical data is designed to have a valid ISBN when the `X` is accepted everywhere and its numerical value is used. It requires though that an error is returned.

I'm therefore in favor of bringing this to the problem-specifications.

**Comment by guygastineau** [comment]
@kotp @NobbZ thank you both for your wisdom.

@Ric0chet-GitHub thank you for bringing this to attention.  Once you open an issue or PR in problem specifications please link it to this issue, so we know we can close it.

Cheers

**Comment by guygastineau** [comment]
I just checked the canonical-data, and the test that @Ric0chet-GitHub wants needs to be added to problem-specifications first.  I am closing this issue.
