### ISSUE TITLE
Run shellcheck automatically on submissions in Bash track as a mentor aid

### ISSUE THREAD

**Issue by bkhl** [exercism/bash#394]
(Continued from https://github.com/exercism/exercism/issues/4806)

I find that when mentoring in the Bash track, a lot of the time, on the early exercises, a lot of my comments are about stuff that would have been caught by [shellcheck](https://www.shellcheck.net/) (static analysis tool for sh/Bash).

How about running it automatically and show the output to the mentor, augmented with ready-to-paste links to the explanations for their warnings on the shellcheck wiki?

This seems like a simple to implement start towards "automatic analysis of solutions to recommend common improvements" mentioned in https://github.com/exercism/exercism/issues/4588

**Comment by glennj** [comment]
The [`bantor`](https://github.com/exercism/bash/blob/master/mentor_tools/bantor) mentoring tool runs shellcheck on a student's solution.

**Comment by guygastineau** [comment]
Yeah, This would be re-implementing some parts of what `bantor` does, but it would happen in the automated-analysis part of exercism.

I think we definitely need to continue supporting bantor, but this idea from @bkhl should be an awesome and relatively easy way to get the bones for automated analysis in place for the track.

**Comment by guygastineau** [comment]
So, in order to do this we need to get set up for for the automated analysis project.

Does anyone want to take lead on this?

I can if no one else wants to, but I figured I would check.

@bkhl this is your idea, so if you want the commit creds it is all yours.

Related:. I have been trying to figure out a way to get ASTs of bash scripts to use for automated analysis.

The python `bashlex` library seemed promising, but it is broken.

Recently I have been considering ripping the wparser out of `shellcheck` (written in Haskell), so we can get the ASTs it makes.

Unfortunately this kind of work is not very well suited for bash, so to get really intelligent analysis we will need to involve another language.  Does anyone have any ideas?

The approach I suggested would be great if we do the extended analysis between the ASTs in Haskell, but I understand it is a bit alienating for those who don't already know it.

Does anybody know how to get the `flex`/`bison` parser actually used in bash?
I figure we could probably parse it's output more easily with more common languages.

Any ideas/info is appreciated.

**Comment by guygastineau** [comment]
Analyzing and comparing ASTs would be for deciding if a solution can be auto-approved.

It is completely unnecessary to inspect it directly for your suggestion.  As I understand it your suggestion is just getting shell check feedback for the mentor without auto-approved.

I think this means it will have to disapprove of every solution and pass on the shell check output (marshalled in json).

Getting the AST for inspection will be something that takes our automated analysis to the next level, but it is unnecessary right now.

**Comment by KartikSoneji** [comment]
> How about running it automatically and show the output to the mentor

Why not run shellcheck on the student's solution before submission?
The C/C++ coding tracks already treat all compiler warnings as errors.
I do not see why a mentor needs to copy-paste the errors and links that shellcheck reports.
Although some errors can be a little hard to grasp, so maybe make the more obscure ones warnings and ask the students to use mentoring if they are not clear on the meaning.

**Comment by glennj** [comment]
> Why not run shellcheck on the student's solution before submission? 

We do: https://exercism-team.slack.com/archives/CB14WUD42/p1632843005049400

It doesn't run until _after_ submission though. And I don't know if it's visible to the mentor. Can you submit a bash exercise, including something you know shellcheck will flag, and them request me for mentoring (I think you can do that, otherwise ping me here or on Slack).

I'd be happy to get your feedback on the wording of what Shellcheck reports.

**Comment by KartikSoneji** [comment]
Let us consider this code sample:
```bash
#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo Usage: $0 "<person>";
    exit 1;
fi

echo "Hello, $1";
```

[Shellcheck](https://www.shellcheck.net/) returns a warning:
```console
$ shellcheck myscript
 
Line 4:
    echo Usage: $0 "<person>";
                ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: (apply this, apply all SC2086)
    echo Usage: "$0" "<person>";
```

But the website still accepts the code _without informing the use about the issue_:
![image](https://user-images.githubusercontent.com/25801283/136292879-624e58d6-e82a-4661-8259-0251d23d0cb3.png)

Shellcheck output is displayed in the "Your iterations" section, but that is easy to miss.
I think it would be more helpful if displayed alongside the code like compiler warnings in C.
They don't have to be errors, so a student can ignore them if they want to, which preserves current behaviour.
For example: (using [`icons/alert-circle.svg`](https://github.com/exercism/website/blob/main/app/javascript/images/icons/alert-circle.svg))

![image](https://user-images.githubusercontent.com/25801283/136302379-a1598854-89d2-48a3-9670-87478b4ada88.png)
