### ISSUE TITLE
Topics: what is leap about?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#65]
In preparation for the launch of the Exercism redesign, we need to decide what topics to list for leap.
See https://github.com/exercism/bash/issues/61 for context.

@ConstantlyLost, @canel-rom1, @dantiel, @deepbsd, @fwten, @mattj-io, @mkrehbs, @patbl, @rpalo, @timmyjose - Having solved this, what would you say that leap is about? Did you struggle with anything in particular? What did you learn?

**Comment by sbfaulkner** [comment]
one thing I just  found  (not sure if intentional or not)...

the tests exercises prior to leap explicitly use base when running the test...
(for example) `run bash bob.sh 'Hello.'`

however, in leap, it it expects leap.sh to be chmod +x
(eg. it simply uses `run ./leap.sh 1996`)

**Comment by deepbsd** [comment]
I think that's a nice catch. 

    On Friday, November 3, 2017 9:22 AM, S. Brent Faulkner <notifications@github.com> wrote:
 

 one thing I just found (not sure if intentional or not)...the tests exercises prior to leap explicitly use base when running the test...
(for example) run bash bob.sh 'Hello.'however, in leap, it it expects leap.sh to be chmod +x
(eg. it simply uses run ./leap.sh 1996)—

**Comment by sjwarner-bp** [comment]
Closed via #128
