### ISSUE TITLE
Topics: what is bob about?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#70]
In preparation for the launch of the Exercism redesign, we need to decide what topics to list for bob.
See https://github.com/exercism/bash/issues/61 for context.

@dantiel, @mkrehbs, @patbl - Having solved this, what would you say that bob is about? Did you struggle with anything in particular? What did you learn?

**Comment by budmc29** [comment]
**About**: Parsing user input and return a response based on that input.
Tags: String, regular_expression, parsing.
Difficulty: 5.
Core?: Maybe.

This was a challenging exercise for bash but gave me tons of fun. I think it's a good one for users that are motivated to learn bash, and they will also get a taste of the sparse online documentation and hopefully reach for the man pages.
I will definitely keep this for a bit later after the user completed more simple bash exercises, but since I did not complete the track maybe this is one of the easiest :D.

**Comment by dantiel** [comment]
i found the exercise annoying (exercismistic) to combine minimal parsing with internal logic (vegetable logic), like the hello world exercise habit, how to make a structure that deals in hello world way with errors, as well. its indeed difficult to find out which is the real bash, as been said


Von: (Mugur) Chirica Bud <notifications@github.com>
Antworten: exercism/bash <reply@reply.github.com>
Datum: 26. September 2017 at 01:45:17
An: exercism/bash <bash@noreply.github.com>
CC: dantiel <dantiel@posteo.de>, Mention <mention@noreply.github.com>
Betreff:  Re: [exercism/bash] Topics: what is bob about? (#70)  

About: Parsing user input and return a response based on that input.
Tags: String, regular_expression, parsing.
Difficulty: 5.
Core?: Maybe.

This was a challenging exercise for bash but gave me tons of fun. I think it's a good one for users that are motivated to learn bash, and they will also get a taste of the sparse online documentation and hopefully reach for the man pages.
I will definitely keep this for a bit later after the user completed more simple bash exercises, but since I did not complete the track maybe this is one of the easiest :D.

**Comment by budmc29** [comment]
@dantiel, what do you think about the proposed tags and difficulty?

I'm also thinking it might be worth to tell the users that are not familiar with bash (or unix in general) to read the man page? I found way better information there than on Google (especially on stack overflow where people mostly posted one liners without much explanation).

**Comment by dantiel** [comment]
mayhaps in bash it could be handy if the exercises wore more template code. yes to read the man pages should papobably be hint as well


Von: (Mugur) Chirica Bud <notifications@github.com>
Antworten: exercism/bash <reply@reply.github.com>
Datum: 26. September 2017 at 10:34:43
An: exercism/bash <bash@noreply.github.com>
CC: dantiel <dantiel@posteo.de>, Mention <mention@noreply.github.com>
Betreff:  Re: [exercism/bash] Topics: what is bob about? (#70)  

@dantiel, what do you think about the proposed tags and difficulty?

I'm also thinking it might be worth to tell the users that are not familiar with bash (or unix in general) to read the man page? I found way better information there than on Google (especially on stack overflow where people mostly posted one liners without much explanation).

**Comment by budmc29** [comment]
Have you seen this? https://github.com/exercism/bash/issues/87

**Comment by sjwarner-bp** [comment]
Closed via #128
