### ISSUE TITLE
We need a rough estimate of difficulty for each exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/bash#75]
We've never really taken a pass through this track to figure out the relative difficulties of each exercise on a scale from 1 - 10 (1 == easy, 10 == hard).

If we could order the exercises so that the difficulty ramps up more gently, we can provide a better experience to those who are working through the exercises.

These are the exercises that we have

- hello-world
- gigasecond
- leap
- hamming
- rna-transcription
- raindrops
- word-count
- bob
- difference-of-squares
- anagram
- pangram
- two-fer
- phone-number

Note that hello-world was pretty difficult, and we've fixed this by simplifying hello world and adding a new exercise, two-fer, which is equivalent to the old one.

/cc @patbl, @dantiel, @mkrehbs, @deepbsd, @canel-rom1, @rpalo, @ConstantlyLost, @fwten, @fbi1714, @timmyjose, @mattj-io, @nielssorensen
You have all done at least some of these. Do you have any ideas about relative difficulties?

**Comment by budmc29** [comment]
hello-world: easy
gigasecond: easy

**Comment by fbi1714** [comment]
hello-world = 1
word-count = 8

**Comment by rpalo** [comment]
I've got some suggestions for topics and difficulties.  Would it be better for me to leave comments on each of the relevant issues?  Or, I can put together a pull request with all of my suggested tweaks to `config.json` to be evaluated all in one place.  Whatever you think is best.

In the meantime:
hello-world = 1
gigasecond = 3
bob = 3
leap = 1
raindrops = 1
difference-of-squares = 1
pangram = 2
anagram = 4
hamming = 2
rna-transcription = 2
two-fer = 1
nucleotide-count = 2
word-count = 3
phone-number = 2
error-handling = 1
atbash-cipher = 5

I tried to pitch these numbers a little low, because I've seen other problems on other language tracks that haven't been ported over (yet 😀 ), and I know there's much harder problems yet to come.

Anyways, let me know if a pull request with updated/modified difficulties and topics would be useful or if I should get to work commenting on each separate issue 👍

**Comment by budmc29** [comment]
> I've got some suggestions for topics and difficulties. Would it be better for me to leave comments on each of the relevant issues?

I think that's a very good idea if you have the time, it would help to explain why you gave each exercise a different rating.

> I can put together a pull request with all of my suggested tweaks to config.json to be evaluated all in one place

That can be done after we have more opinions about the difficulty of each exercise from various developers.

**Comment by ltrainpr** [comment]
Looking to learn quite a bit more about bash shell scripting in 2018.  Poked at Bash track yesterday.  Hello World exercise was easy enough.  Currently stuck on first test of gigasecond exercise as it requires specific time `[ "$output" == 'Thu Jan 1 01:46:40 UTC 2043' ]` even though what's being passed in is `'2011-04-25Z'`.  Is this on purpose?

**Comment by rpalo** [comment]
@ltrainpr I just double-checked to make sure nothing was funky.  It looks like, since you're adding seconds to things, you need to pick *some* time for the initial date, even if none is provided.  So your script should default to midnight of the date provided if none is given.  When you default the time to midnight, that first test ends up at the correct time of 1:46:40.  It's possible that this should be documented better in the prompt.  I'm not sure.  I'll take a look.

Either way, if you get hung up on this or any of the other Bash challenges, let me know and I'd be happy to try and provide some help :smile:

**Comment by ltrainpr** [comment]
Thank you for your help @rpalo.  I was able to solve the problem with the additional info (setting default time to midnight) you provided.  The only other obstacle I faced was syntax.  See [this](https://stackoverflow.com/questions/48114627/why-am-i-getting-date-illegal-time-format) stack overflow question regarding my syntax problem.

My suggestion is to include in the `README` that the default time needs to be set to midnight.

**Comment by kytrinyx** [comment]
We can have a `hints.md` file for the exercise that includes this information, then regenerate the README using the `configlet` binary.

See https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md for details

**Comment by sjwarner-bp** [comment]
Closed via #128
